"""add review_count to product

Revision ID: 6cf1b9649788
Revises: 70e5f8ae447d
Create Date: 2025-07-19 14:04:05.829404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf1b9649788'
down_revision: Union[str, None] = '70e5f8ae447d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('idx_chat_message_history_session_id'), table_name='chat_message_history')
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review_count')
    #op.create_index(op.f('idx_chat_message_history_session_id'), 'chat_message_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
