"""fresh

Revision ID: cedde5f19234
Revises: 
Create Date: 2025-07-19 17:00:29.720957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cedde5f19234'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('chat_message_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_history_session_id'), 'chat_message_history', ['session_id'], unique=False)
     
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_index(op.f('ix_chat_message_history_session_id'), table_name='chat_message_history')
    op.drop_table('chat_message_history')
    
    # ### end Alembic commands ###
